# Generated by Django 5.2.5 on 2025-08-30 19:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Название категории')),
                ('type', models.CharField(choices=[('income', 'Доход'), ('expense', 'Расход'), ('transfer', 'Перевод')], default='expense', max_length=20, verbose_name='Тип категории')),
                ('color', models.CharField(default='#3682f6', max_length=7, verbose_name='Цвет категории')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='Иконка категории')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_system', models.BooleanField(default=False, verbose_name='Системная категория')),
                ('budget_limit', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True, verbose_name='Лимит бюджета')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='categories.category')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['type', 'name'],
            },
        ),
    ]
