# Generated by Django 5.2.7 on 2025-10-22 20:01

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0003_remove_account_accent_color_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RegularOperation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="Название операции"),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=19,
                        validators=[django.core.validators.MinValueValidator(0.01)],
                        verbose_name="Сумма",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("income", "Доход"), ("expense", "Расход")],
                        max_length=20,
                        verbose_name="Тип операции",
                    ),
                ),
                ("start_date", models.DateTimeField(verbose_name="Дата начала")),
                (
                    "end_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата окончания"
                    ),
                ),
                (
                    "period_type",
                    models.CharField(
                        choices=[
                            ("day", "Ежедневно"),
                            ("week", "Еженедельно"),
                            ("month", "Ежемесячно"),
                        ],
                        max_length=20,
                        verbose_name="Периодичность",
                    ),
                ),
                (
                    "period_interval",
                    models.PositiveIntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Интервал",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активна"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "from_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="regular_operations_outgoing",
                        to="accounts.account",
                    ),
                ),
                (
                    "to_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="regular_operations_incoming",
                        to="accounts.account",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="regular_operations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Регулярная операция",
                "verbose_name_plural": "Регулярные операции",
                "ordering": ["-created_at"],
            },
        ),
    ]
