# Generated by Django 5.2.5 on 2025-11-03 11:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("regular_operations", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="regularoperation",
            name="amount",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=19,
                validators=[django.core.validators.MinValueValidator(0.01)],
                verbose_name="Сумма",
            ),
        ),
    ]
