# Generated by Django 5.2.6 on 2025-11-10 17:23

import uuid

from django.db import migrations
import model_utils.fields


class Migration(migrations.Migration):
    dependencies = [
        ("regular_operations", "0002_alter_regularoperation_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="regularoperation",
            name="id",
            field=model_utils.fields.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
