# Generated by Django 5.2.6 on 2025-11-10 17:31

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):
    dependencies = [
        ("regular_operations", "0003_alter_regularoperation_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="regularoperation",
            name="deleted_at",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="regularoperation",
            name="created_at",
            field=model_utils.fields.AutoCreatedField(
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="created_at",
            ),
        ),
        migrations.AlterField(
            model_name="regularoperation",
            name="updated_at",
            field=model_utils.fields.AutoLastModifiedField(
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="updated_at",
            ),
        ),
    ]
