# Generated by Django 5.2.6 on 2025-11-15 11:08

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("regular_operations", "0004_regularoperation_deleted_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="regularoperation",
            name="is_active",
        ),
        migrations.AddField(
            model_name="regularoperation",
            name="active_before",
            field=models.DateField(default=datetime.date(9999, 12, 31), verbose_name="Активна"),
        ),
    ]
