# Generated by Django 5.2.6 on 2025-11-09 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("regular_operations", "0002_alter_regularoperation_amount"),
        ("scenarios", "0003_alter_scenariorule_amount"),
        ("transactions", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="operation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="regular_operations.regularoperation",
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="scenario_rule",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="scenarios.scenariorule",
            ),
        ),
    ]
