# Generated by Django 5.2.6 on 2025-11-15 11:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transactions", "0004_alter_transaction_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="planned_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Дата запланированной операции"
            ),
        ),
    ]
