# Generated by Django 5.2.5 on 2025-09-30 08:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Название счета')),
                ('type', models.CharField(choices=[('savings', 'Накопления'), ('checking', 'Расчетный'), ('credit', 'Кредитный'), ('investment', 'Инвестиционный'), ('loan', 'Долг')], max_length=20, verbose_name='Тип счета')),
                ('current_balance', models.DecimalField(decimal_places=4, default=0, max_digits=19, verbose_name='Текущий баланс')),
                ('target_amount', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True, verbose_name='Целевая сумма')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('accent_color', models.CharField(blank=True, max_length=7, verbose_name='Цвет акцента')),
                ('gradient_theme', models.CharField(choices=[('default', 'По умолчанию'), ('mountains', 'Горы'), ('forest', 'Лес'), ('travel', 'Путешествия'), ('technology', 'Технология')], default='default', max_length=20, verbose_name='Градиент')),
                ('custom_image_url', models.URLField(blank=True, verbose_name='URL кастомного изображения')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Счет',
                'verbose_name_plural': 'Счета',
                'ordering': ['created_at'],
            },
        ),
    ]
