# Generated by Django 5.2.5 on 2025-10-21 18:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="account",
            name="accent_color",
        ),
        migrations.RemoveField(
            model_name="account",
            name="custom_image_url",
        ),
        migrations.RemoveField(
            model_name="account",
            name="gradient_theme",
        ),
        migrations.AlterField(
            model_name="account",
            name="type",
            field=models.CharField(
                choices=[
                    ("main", "Главные"),
                    ("purpose", "Цель"),
                    ("accumulation", "Накопления"),
                    ("debt", "Долг"),
                    ("reserve", "Резерв"),
                ],
                max_length=20,
                verbose_name="Тип счета",
            ),
        ),
        migrations.AlterModelTable(
            name="account",
            table="accounts",
        ),
    ]
