# Generated by Django 5.2.6 on 2025-11-03 23:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_remove_account_accent_color_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="current_balance",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=19,
                verbose_name="Текущий баланс",
            ),
        ),
    ]
