# Generated by Django 5.2.6 on 2025-11-15 19:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_alter_account_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="current_balance_updated",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                verbose_name="Время обновления баланса",
            ),
        ),
    ]
