# Generated by Django 5.2.5 on 2025-08-30 19:02

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScenarioRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('fixed', 'Фиксированная сумма'), ('percentage', 'Процент')], max_length=20, verbose_name='Тип правила')),
                ('amount', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True, verbose_name='Фиксированная сумма')),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Процент')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок применения')),
            ],
            options={
                'verbose_name': 'Правило сценария',
                'verbose_name_plural': 'Правила сценария',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PaymentScenario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Название сценария')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('execution_order', models.IntegerField(default=0, verbose_name='Порядок выполнения')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenarios', to='accounts.account')),
            ],
            options={
                'verbose_name': 'Платежный сценарий',
                'verbose_name_plural': 'Платежные сценарии',
                'ordering': ['execution_order'],
            },
        ),
    ]
