# Generated by Django 5.2.7 on 2025-10-22 20:01

from django.db import migrations, models
import django.db.models.deletion


def cleanup_orphan_scenarios(apps, schema_editor):
    Scenario = apps.get_model("scenarios", "Scenario")
    Scenario.objects.filter(operation__isnull=True).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("regular_operations", "0001_initial"),
        ("scenarios", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="Scenario",
            name="operation",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scenario",
                to="regular_operations.regularoperation",
                verbose_name="Регулярная операция",
            ),
        ),
        migrations.RunPython(cleanup_orphan_scenarios, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="Scenario",
            name="operation",
            field=models.OneToOneField(
                blank=False,
                null=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scenario",
                to="regular_operations.regularoperation",
                verbose_name="Регулярная операция",
            ),
        ),
    ]
