# Generated by Django 5.2.5 on 2025-11-03 11:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scenarios", "0002_paymentscenario_operation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scenariorule",
            name="amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=19,
                null=True,
                verbose_name="Фиксированная сумма",
            ),
        ),
    ]
